//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AlumnoMaterias
    {
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string documento { get; set; }
        public Nullable<short> edad { get; set; }
        public int idAlumno { get; set; }
        public int idMateria { get; set; }
        public int horas { get; set; }
        public string Expr1 { get; set; }
    }
}
